ball_answers = [
    "🌞 It is certain, just relax and it will come/happen.",
    "🔮 I have determined that, YES!",
    "🖕 Not to be a cunt, but no!",
    "🌟 Without a shred of doubt !!",
    "👍 Yes definitely, no need to ask anymore for today.",
    "🌈 You're so lucky, yet the answer is no.",
    "👌 You may rely on it.",
    "🚧 404\n\nAnswer not found.",
    "👀 If it exists, there is porn of it — no exceptions.",
    "👍 As I see it... yes, don't worry about it anymore.",
    "🤷‍♀️ I cannot find a satisfactory answer on the internet either.",
    "🤔 Most likely, but you have to take the first step.",
    "👍 Outlook is good, do your best!",
    "👍 Yes.",
    "🖥️ I asked ChatGPT and he doesn't know either.",
    "👽 I͢fͪ yͧo̞u̎ c̮ͭa̴ͫn̛̗̅'t̼̹̀ rͣ̒e̤̿a̜ͣd͕͗ ṯ̭͗h́̉͝i̵̥͠ș̽ͤ m̺̤ͧę̏̌s̫͓̕s̟̐̀â͟ͅg̡̖͛ḛ̼̉, p͙̞̽l̪̤͞e͏͙͊ă̳̟s̳͋ͬé̎̑... \ns̞͑̂e͖͋́e̓̑̾ a̳̎̊ D͙̹ͅo̬ͦ̍c̔͊͟t̼̹̀o͏̄̑r̵̝ͦ a̰̳̔n̛̗̅d̮̔͘ a̒́͠s̃́̓k͓͍̿ f̰͐ͭo̳̚͢rͭ̏͏ b̿̐̍e͍̪͋ṭ̑̏t̶̗̙e̝ͮ͊ṙͧ͠ g̐͆͠ḷ͗͝aͫ̌̉s̖̩̽s̲̏̌e̴̓͗s̞̃̎",
    "🌟 Signs point to yes, but with some difficulty.",
    "🙅‍♀️ I'm busy right now, can you come by later? \nThank you.",
    "🌊 Hazy reply, try again after a cold shower.",
    "🥦 You should know that I'm vegan, so I can't really tell the difference.",
    "🔮 Ask again later, for now try to relax and think about something else.",
    "🤫 Follow this tip: if they can't see you, they won't know about it.",
    "🤔 There are a lot of possibilities, just do it, wisely.",
    "🤔 Better not tell you now, you'll understand later.",
    "🔮 Cannot predict now, ask anything else.",
    "🧘‍♂️ Concentrate, breathe, close your eyes and, ask again.",
    "🔍 Learn to google, then, google-it!",
    "😊 Seek joy first and foremost!",
    "🚫 Thou shall not pass.",
    "🙅‍♀️ Don't count on it, better do something else for now.",
    "⏳ All things must pass. This too.",
    "👎 My reply is no, have a nice day.",
    "👻 My imaginary friends said no, brb.",
    "🤔 As hard as it might be to accept, the answer is, maybe.",
    "⚠️ There might be problems, be ready.",
    "👎 Very doubtful, better don't get attached.",
    "👋 That's a lot of work and responsibility, we'll miss you.",
    "🤷‍♀️ Never, just give up and be happy as you are.",
    "☀️ Tip of the day: you need more sunlight.",
    "📴 Forget about it, turn on airplane mode and relax offline for a while.",
    "👩‍👦 Go and ask your mum.",
    "乁( ⁰͡ Ĺ̯ ⁰͡ ) ㄏ who knows, who cares.",
    "🙃 ¿pɐǝɹ oʇ pɐǝɥ ɹnoʎ uɹnʇ ʇsnɾ noʎ pᴉp",
    "🚭 Please do not smoke marijuana, even if it's legal."
]
