FORTUNE = [
    "Now is the time to try something new.",
    "Be brave. Ask for extra chili sauce.",
    "The best version of you is unfolding —don’t interrupt the process.",
    "Change is no longer coming; it’s already here.",
    "You are a mirror; reflect wisely.",
    "Your *pron* addiction will soon be legendary.",
    "Greatness isn’t loud —it’s consistent.",
    "Your light will guide others through their darkness.",
    "Destiny says: take a nap, then conquer the world, or eat a sandwich.",
    "Your lucky number is... lost in traffic.",
    "Good things come to those who wait, without complaining.",
    "Someone is silently inspired by your journey.",
    "A door long closed will creak open with an unexpected fresh breeze.",
    "Dance, even when there’s no music —especially then.",
    "Your creativity will make you famous.",
    "The future has been waiting for you to believe.",
    "Let laughter be your daily revolution.",
    "You’ll misplace your phone… while talking on it.",
    "When the moon wanes, so will your doubt.",
    "Caution: You may soon be the reason someone Googles something weird.",
    "A forgotten talent will soon demand revival.",
    "You will soon find the TV remote… in the fridge, behind the frozen peas.",
    "Get ready to receive something special.",
    "Soon you will be asked a question only your heart can answer.",
    "An email, long delayed, is on its way to you.",
    "The next stranger you meet knows a key to your destiny.",
    "Life will soon serve you dessert first.",
    "That embarrassing thing you did? They *did* notice.",
    "A symbol will appear three times —pay attention.",
    "Your perseverance will pay off soon™",
    "Don’t fear failure; fear never trying.",
    "A leap of faith will land better than you think.",
    "Beware of unsolicited compliments.",
    "A shadow from the past seeks closure —will you answer?",
    "You’re not behind —you’re building.",
    "The stars are aligning in your favour —prepare for acceleration.",
    "You’ll finally understand that weird advice you once ignored.",
    "You will soon question your life choices while holding a taco.",
    "Someone will fart in an elevator and you’ll be blamed for it.",
    "Your significant other just liked their ex’s post. Stay strong.",
    "Your next epiphany will involve cheese. Don’t ask why. Enjoy.",
    "You will survive the next family gathering, barely...",
    "You’ll win an argument by quoting chatGPT. Here’s a summary of your question.",
    "Avoid clowns this week. Seriously, just don’t.",
    "The universe says: stop texting your ex. Again.",
    "You’ll pretend to understand something important —and get away with it.",
    "A pigeon will soon change the course of your day.",
    "Your next deep thought will happen on the toilet.",
    "You will soon master the art of passive-aggressive applause.",
    "Don’t trust the guy with too many crystals in his pockets.",
    "You’re not weird —they’re just boring.",
    "You’ll soon experience existential dread... in a supermarket aisle.",
    "The Wi-Fi will fail at the worst possible moment. Be ready.",
    "You’re about to say something dumb —and it will be recorded.",
    "Help, I am currently living in a cookie factory.",
    "Soon, you’ll meet someone who thinks sociology is a sound career plan.",
    "Your next crush will be emotionally unavailable —but with great hair.",
    "You will forget why you entered a room... again.",
    "Fate has you on hold. Please enjoy this mediocre fortune while it lasts.",
    "You are exactly where you need to be to grow strong.",
    "Your future includes an awkward high-five–versus–fist bump situation.",
    "A pleasant surprise is waiting for you",
    "A quiet mind opens most legs.",
    "A beautiful, smart, and loving person will be coming into your life.",
    "You are the plot twist someone never saw coming.",
    "You’ll soon meet someone who thinks pineapple belongs on pizza —keep calm.",
    "The mountain is steep, but your legs are strong.",
    "Listen tonight —the wind carries a message just for you.",
    "A sock you lost will reappear when you least expect it.",
    "Your relationship status is about to change.",
    "Success follows those who dare to wake-up.",
    "A kind heart is your greatest asset —guard it, use it, don’t abuse it.",
    "The storm you’re facing now is watering your near future.",
    "You’re one bad decision away from finding true love.",
    "You’ll win an argument using a meme you saved in your phone.",
    "The seeds you plant today will bloom in unexpected ways.",
    "Even a grain of sand is of valid help when building a bridge.",
    "Take a leap of faith and say hi to someone new today.",
    "At the edge of risk lies your transformation."
]
