card_deck = [
    ":small_red_triangle: » Upright card meaning\n**0 The Fool:** ```bf\nAct impulsively, follow your feelings, surprise, wonder, excitement, take opportunities that arise.```",
    ":small_red_triangle_down: » Downright card meaning\n**0 The Fool:** ```bf\nDifficulty believing in your instincts, fear of stepping into the unknown, do not be reckless.```",
    ":small_red_triangle: » Upright card meaning\n**1 The Magician:** ```bf\nPower, Strength, Being in control of one’s life. Transforming old situations, bringing in new ones. A burst of energy, Creativity, Focused Will.```",
    ":small_red_triangle_down: » Downright card meaning\n**1 The Magician:** ```bf\nNatural expression of energy blocked. Inner resistance. Arrogance. Misuse of personal power.```",
    ":small_red_triangle: » Upright card meaning\n**2 The High Priestess:** ```bf\nA time for quiet, for looking inward. Seek peace. Use intuition and feeling. Peace and joy. Possibly, a lover who needs solitude or is avoiding commitment.```",
    ":small_red_triangle_down: » Downright card meaning\n**2 The High Priestess:** ```bf\nA time for action, for involvements with others. Commitment in romance.```",
    ":small_red_triangle: » Upright card meaning\n**3 The Empress:** ```bf\nPassion, Love of nature, Motherhood. Joyous Activity.```",
    ":small_red_triangle_down: » Downright card meaning\n**3 The Empress:** ```bf\nPassion blocked. Difficulty expressing oneself. Problems with one’s mother.```",
    ":small_red_triangle: » Upright card meaning\n**4 The Emperor:** ```bf\nInfluence of Society, law. Resurgence of energy. Sexual potency. Arrogance. Insensitivity. Energy and Desire.```",
    ":small_red_triangle_down: » Downright card meaning\n**4 The Emperor:** ```bf\nBlocked possibility. Development of sensitivity.```",
    ":small_red_triangle: » Upright card meaning\n**5 The Hierophant:** ```bf\nTradition, community and teachings. Conformity. Marriage, or any solemn commitment.```",
    ":small_red_triangle_down: » Downright card meaning\n**5 The Hierophant:** ```bf\nSocial pressure. Doctrines and ideas that have lost meaning. Originality. Gullibility.```",
    ":small_red_triangle: » Upright card meaning\n**6 The Lovers:** ```bf\nThe importance of love. Depending on the place in the spread, the state of a specific relationship.```",
    ":small_red_triangle_down: » Downright card meaning\n**6 The Lovers:** ```bf\na relationship ending, trouble in a relationship. Lack of love. Insecurity, loneliness. Loss of Balance.```",
    ":small_red_triangle: » Upright card meaning\n**7 The Chariot:** ```bf\nWillpower in dealing with problems. Will to continue. Deep fear driving a person. Triumph over fear.```",
    ":small_red_triangle_down: » Downright card meaning\n**7 The Chariot:** ```bf\nLack of will. Passivity or weakness. It may be best to let things run their course.```",
    ":small_red_triangle: » Upright card meaning\n**8 Strength:** ```bf\nInner strength. Love and gentleness. Confidence. Ability to give love.```",
    ":small_red_triangle_down: » Downright card meaning\n**8 Strength:** ```bf\nFeeling blocked from one’s power. Weak. Overwhelmed. Meditation or some form of relaxation may help restore strength.```",
    ":small_red_triangle: » Upright card meaning\n**9 The Hermit:** ```bf\nWithdrawal from outside interests. Self-reliance. Self-creation. Developing one’s personality. Gaining wisdom. Powerful dreams.```",
    ":small_red_triangle_down: » Downright card meaning\n**9 The Hermit:** ```bf\nInvolvement with others. Fear of loneliness. Disturbing dreams. A desire to not grow up.```",
    ":small_red_triangle: » Upright card meaning\n**10 The Wheel of Fortune:** ```bf\nChange of circumstances. Taking hold of one’s life. Grabbing hold of fate. Time to take what life has given you.```",
    ":small_red_triangle_down: » Downright card meaning\n**10 The Wheel of Fortune:** ```bf\nDifficulty adjusting to changes. Resistance to change.```",
    ":small_red_triangle: » Upright card meaning\n**11 Justice:** ```bf\nExamine your life, weigh things in the balance. A relationship is going badly. Analysis. Take a balanced view.```",
    ":small_red_triangle_down: » Downright card meaning\n**11 Justice:** ```bf\nDo not act out of habit. Imbalance. You may be acting unfairly. Trying to avoid an honest evaluation.```",
    ":small_red_triangle: » Upright card meaning\n**12 The Hanged Man:** ```bf\nAttachment. Deep spiritual awareness. Independence.```",
    ":small_red_triangle_down: » Downright card meaning\n**12 The Hanged Man:** ```bf\nBeing overly influenced by outside ideas. Pressure to conform. Demands. Sacrificing something to get past hangups. Lack of purpose.```",
    ":small_red_triangle: » Upright card meaning\n**13 Death:** ```bf\nRarely refers to physical death. More about ideas about death. Psychologically, letting go. New opportunities.```",
    ":small_red_triangle_down: » Downright card meaning\n**13 Death:** ```bf\nResisting change. Stagnation. Inertia. Pain of giving something up.```",
    ":small_red_triangle: » Upright card meaning\n**14 Alchemy:** ```bf\nMeasurement and combination. Do not allow setbacks to turn enthusiasm into its mirror image of dejection. Take control. Moderation.```",
    ":small_red_triangle_down: » Downright card meaning\n**14 Alchemy:** ```bf\nGoing to extremes. Excessive behavior. Conserve energy. A person out of control.```",
    ":small_red_triangle: » Upright card meaning\n**15 The Devil:** ```bf\nSomething exciting, possibly dangerous or forbidden. Temptation. Physical gratification. Exploring darker feelings. Wild action opens up new areas in life.```",
    ":small_red_triangle_down: » Downright card meaning\n**15 The Devil:** ```bf\nResisting temptations. Not a time for sensuality. Fear of one’s own decisions.```",
    ":small_red_triangle: » Upright card meaning\n**16 The Tower:** ```bf\nLong-standing activity or approach that may bring about disaster if continued. Pressure building up. Long-buried emotions let loose. News. A flash of understanding.```",
    ":small_red_triangle_down: » Downright card meaning\n**16 The Tower:** ```bf\nSimilar to upright meanings, but less severe. A shaking up. A minor disturbance.```",
    ":small_red_triangle: » Upright card meaning\n**17 The Star:** ```bf\nRenewal. Reality and feeling. Cleansing. Humility. Hope.```",
    ":small_red_triangle_down: » Downright card meaning\n**17 The Star:** ```bf\nFears for the future. Isolation. Tension or anxiety. Hope.```",
    ":small_red_triangle: » Upright card meaning\n**18 The Moon:** ```bf\nImagination. Fantasies, daydreams, strong dreams. The sources of creativity.```",
    ":small_red_triangle_down: » Downright card meaning\n**18 The Moon:** ```bf\nThe time to return to \"solar\", rational activities. Conscious mind blocking the unconscious.```",
    ":small_red_triangle: » Upright card meaning\n**19 The Sun:** ```bf\nJoy and simplicity. Life is wonderful. Energy. Activity, excitement, optimism. Rational approach. Confidence. Sexual Desire.```",
    ":small_red_triangle_down: » Downright card meaning\n**19 The Sun:** ```bf\nSun is clouded over. Day-to-day problems, though happiness remains. Loss of confidence. Frustration.```",
    ":small_red_triangle: » Upright card meaning\n**20 Aeon:** ```bf\nRenewal. Optimism, in spite of a painful period of change. Change. Spontaneity. All things are possible. Old world seen through new eyes.```",
    ":small_red_triangle_down: » Downright card meaning\n**20 Aeon:** ```bf\nRebirth. Resisting change. A new life, possibly not acknowledged.```",
    ":small_red_triangle: » Upright card meaning\n**21 The Universe:** ```bf\nSuccess. Becoming happier, more fulfilled. Recovery from illness. An exciting future. Stagnation. Lack of willpower and confidence.```",
    ":small_red_triangle_down: » Downright card meaning\n**21 The Universe:** ```bf\nStagnation. Lack of willpower and confidence. Self-defined limitations. Resistance or opposition.```",
    ":small_red_triangle: » Upright card meaning\n**Ace of Wands:** ```bf\nGift of fire. Energy, optimism, confidence. Desire. Beginnings.```",
    ":small_red_triangle_down: » Downright card meaning\n**Ace of Wands:** ```bf\nLack of focus. Scattered or confused efforts. Pessimism.```",
    ":small_red_triangle: » Upright card meaning\n**Two of Wands:** ```bf\nPower, Strong Will. The power of spiritual truth.```",
    ":small_red_triangle_down: » Downright card meaning\n**Two of Wands:** ```bf\nVoluntarily giving up a position of power. Seeking adventures. Misuse of power.```",
    ":small_red_triangle: » Upright card meaning\n**Three of Wands:** ```bf\nActing in harmony with nature. Purpose. Good fortune.```",
    ":small_red_triangle_down: » Downright card meaning\n**Three of Wands:** ```bf\nBeing out of harmony with the situation. Difficulty in finding the point of life or in discovering worthy goals.```",
    ":small_red_triangle: » Upright card meaning\n**Four of Wands:** ```bf\nNew life. Take action at the right moment. Excitement and growth.```",
    ":small_red_triangle_down: » Downright card meaning\n**Four of Wands:** ```bf\nErrors. Impatient for new start. Wait for genuine opportunity.```",
    ":small_red_triangle: » Upright card meaning\n**Five of Wands:** ```bf\nStrife and battle, without hatred or bitterness. Avoidance.```",
    ":small_red_triangle_down: » Downright card meaning\n**Five of Wands:** ```bf\nPersonal and aggressive conflicts. Bitterness towards others.```",
    ":small_red_triangle: » Upright card meaning\n**Six of Wands:** ```bf\nTriumph. Confidence and firm action will lead to triumph. Inspiration.```",
    ":small_red_triangle_down: » Downright card meaning\n**Six of Wands:** ```bf\nLoss of belief. Negative attitude can lead to failure.```",
    ":small_red_triangle: » Upright card meaning\n**Seven of Wands:** ```bf\nCourage and daring - possibly, the courage to retreat. Using one’s power for transformation.```",
    ":small_red_triangle_down: » Downright card meaning\n**Seven of Wands:** ```bf\nLoss of nerve. Hesitation. Seek an alternative, possibly reconciliation.```",
    ":small_red_triangle: » Upright card meaning\n**Eight of Wands:** ```bf\nDefinite movement. Progress. A worthy goal. Finding direction in life. Development of a new love affair.```",
    ":small_red_triangle_down: » Downright card meaning\n**Eight of Wands:** ```bf\nScattered energy. Contradictory activities. Fear of taking action. Shyness, or jealousy.```",
    ":small_red_triangle: » Upright card meaning\n**Nine of Wands:** ```bf\nGreat energy. Arrogance, especially toward those who feel weak. Life’s resiliency.```",
    ":small_red_triangle_down: » Downright card meaning\n**Nine of Wands:** ```bf\nWeakness. Passivity. Arrogance or misuse of power.```",
    ":small_red_triangle: » Upright card meaning\n**Ten of Wands:** ```bf\nOppression. Depression. Transformation from cruelty to liberation. Possible fall.```",
    ":small_red_triangle_down: » Downright card meaning\n**Ten of Wands:** ```bf\nEmerging from a bad situation. Wisdom gained through adversity.```",
    ":small_red_triangle: » Upright card meaning\n**Mother of Wands in the East (Kali):** ```bf\nA wild, female energy. Dark power, sexual energy.```",
    ":small_red_triangle_down: » Downright card meaning\n**Mother of Wands in the East (Kali):** ```bf\nKali-like energy suppressed. Destructiveness outweighs love and joy.```",
    ":small_red_triangle: » Upright card meaning\n**Father of Wands in the East (Brahma):** ```bf\nA calm person, possibly stuffy. A rooted quality that gives strength.```",
    ":small_red_triangle_down: » Downright card meaning\n**Father of Wands in the East (Brahma):** ```bf\nSnobbishness, especially intellectual. Devotion. Doubts, weakness, confusion.```",
    ":small_red_triangle: » Upright card meaning\n**Daughter of Wands in the East (Radha):** ```bf\nAbundance. Joy. Good Sense. Culture.```",
    ":small_red_triangle_down: » Downright card meaning\n**Daughter of Wands in the East (Radha):** ```bf\nUnfulfilled potential.```",
    ":small_red_triangle: » Upright card meaning\n**Son of Wands in the East (Krishna):** ```bf\nLove of life. Interest in the arts. Trickster. Attractiveness.```",
    ":small_red_triangle_down: » Downright card meaning\n**Son of Wands in the East (Krishna):** ```bf\nDifficulty. Conflict. Problems may bring out depths in a person.```",
    ":small_red_triangle: » Upright card meaning\n**Ace of Cups:** ```bf\nHappiness. Love, joy, optimism. Love flowing openly between two people.```",
    ":small_red_triangle_down: » Downright card meaning\n**Ace of Cups:** ```bf\nHappiness is blocked. Trouble communicating. Value of life questioned.```",
    ":small_red_triangle: » Upright card meaning\n**Two of Cups:** ```bf\nRelationship. Possibly, the need to make a commitment.```",
    ":small_red_triangle_down: » Downright card meaning\n**Two of Cups:** ```bf\nQuarreling or jealousy. Uncertain future. Lack of commitment.```",
    ":small_red_triangle: » Upright card meaning\n**Three of Cups:** ```bf\nGreat feeling. Extreme joy that can turn to tears.```",
    ":small_red_triangle_down: » Downright card meaning\n**Three of Cups:** ```bf\nFeelings dammed up. Instability.```",
    ":small_red_triangle: » Upright card meaning\n**Four of Cups:** ```bf\nFind a moment of peace and balance. Action is possible and will lead to growth.```",
    ":small_red_triangle_down: » Downright card meaning\n**Four of Cups:** ```bf\nLoss of balance. Suppressed emotions.```",
    ":small_red_triangle: » Upright card meaning\n**Five of Cups:** ```bf\nBe patient. Confusion and disappointment are exaggerated.```",
    ":small_red_triangle_down: » Downright card meaning\n**Five of Cups:** ```bf\nComing out of disappointment. A realistic view of the past.```",
    ":small_red_triangle: » Upright card meaning\n**Six of Cups:** ```bf\nHappiness. Loving and being loved. Balance and peace.```",
    ":small_red_triangle_down: » Downright card meaning\n**Six of Cups:** ```bf\nThe happy moment may be passing. Not recognizing happiness. Unbalanced or excessive behavior.```",
    ":small_red_triangle: » Upright card meaning\n**Seven of Cups:** ```bf\nBeware of arrogance and complacency. Fantasies.```",
    ":small_red_triangle_down: » Downright card meaning\n**Seven of Cups:** ```bf\nHidden problems emerging. More realistic outlook.```",
    ":small_red_triangle: » Upright card meaning\n**Eight of Cups:** ```bf\nFailure. Arrogance and greed. Accept help from others.```",
    ":small_red_triangle_down: » Downright card meaning\n**Eight of Cups:** ```bf\nHidden joy. New happiness. Positive change.```",
    ":small_red_triangle: » Upright card meaning\n**Nine of Cups:** ```bf\nFortune. Wealth. Emotional breakthrough. Generosity.```",
    ":small_red_triangle_down: » Downright card meaning\n**Nine of Cups:** ```bf\nStinginess. Loss.```",
    ":small_red_triangle: » Upright card meaning\n**Ten of Cups:** ```bf\nSuccessful development, with some effort required.```",
    ":small_red_triangle_down: » Downright card meaning\n**Ten of Cups:** ```bf\nSuccess Blocked. Negativity, apathy.```",
    ":small_red_triangle: » Upright card meaning\n**Mother of Cups in the North (Venus of Willendorf):** ```bf\nEarthy, Plain, Honest person. Matriarch. Ancient Forces.```",
    ":small_red_triangle_down: » Downright card meaning\n**Mother of Cups in the North (Venus of Willendorf):** ```bf\nSomeone out of touch with physical realities.```",
    ":small_red_triangle: » Upright card meaning\n**Father of Cups in the North (Odin):** ```bf\nA powerful, domineering person. Intelligence. Creativity. Generous and Loving.```",
    ":small_red_triangle_down: » Downright card meaning\n**Father of Cups in the North (Odin):** ```bf\nFather’s power disrupted.```",
    ":small_red_triangle: » Upright card meaning\n**Daughter of Cups in the North (Brigid):** ```bf\nCalmness and radiance. Peacefulness, and strength of power.```",
    ":small_red_triangle_down: » Downright card meaning\n**Daughter of Cups in the North (Brigid):** ```bf\nLoss of self-assurance. Importance of personal history ignored.```",
    ":small_red_triangle: » Upright card meaning\n**Son of Cups in the North (Parsival):** ```bf\nSweet-tempered, but naive person. A good heart. A test.```",
    ":small_red_triangle_down: » Downright card meaning\n**Son of Cups in the North (Parsival):** ```bf\nAvoiding responsibility. Callousness.```",
    ":small_red_triangle: » Upright card meaning\n**Ace of Swords:** ```bf\nIntelligence. Clear thinking. Powerful personality or emotions.```",
    ":small_red_triangle_down: » Downright card meaning\n**Ace of Swords:** ```bf\nAnger. Aggression. Distorted thinking.```",
    ":small_red_triangle: » Upright card meaning\n**Two of Swords:** ```bf\nTranquility. Opportunity for prospering.```",
    ":small_red_triangle_down: » Downright card meaning\n**Two of Swords:** ```bf\nDisruption. Seek tranquility within.```",
    ":small_red_triangle: » Upright card meaning\n**Three of Swords:** ```bf\nOppressive situations. Mourning. Sorrow.```",
    ":small_red_triangle_down: » Downright card meaning\n**Three of Swords:** ```bf\nDifficulty accepting loss. The natural cycle will bring renewal.```",
    ":small_red_triangle: » Upright card meaning\n**Four of Swords:** ```bf\nA moment of calm.```",
    ":small_red_triangle_down: » Downright card meaning\n**Four of Swords:** ```bf\nMovement away from silence and peace. New beginnings or old troubles.```",
    ":small_red_triangle: » Upright card meaning\n**Five of Swords:** ```bf\nAn overwhelming situation. Need to hold onto principles until the time comes to make a change.```",
    ":small_red_triangle_down: » Downright card meaning\n**Five of Swords:** ```bf\nSituation growing better, with courage and persistence.```",
    ":small_red_triangle: » Upright card meaning\n**Six of Swords:** ```bf\nNeed for objectivity and honesty.```",
    ":small_red_triangle_down: » Downright card meaning\n**Six of Swords:** ```bf\nIdealism used for selfish ends.```",
    ":small_red_triangle: » Upright card meaning\n**Seven of Swords:** ```bf\nDepression. Possibly, the need to leave a situation for new possibilities.```",
    ":small_red_triangle_down: » Downright card meaning\n**Seven of Swords:** ```bf\nAttempting to deal with feelings of uselessness.```",
    ":small_red_triangle: » Upright card meaning\n**Eight of Swords:** ```bf\nInterference. Gossip. Help or Advice.```",
    ":small_red_triangle_down: » Downright card meaning\n**Eight of Swords:** ```bf\nNo interference. Avoiding responsibility.```",
    ":small_red_triangle: » Upright card meaning\n**Nine of Swords:** ```bf\nCruelty. Feeling like a victim.```",
    ":small_red_triangle_down: » Downright card meaning\n**Nine of Swords:** ```bf\nRelief from cruel conditions. Confusion. Manipulation.```",
    ":small_red_triangle: » Upright card meaning\n**Ten of Swords:** ```bf\nPain, confusion. Personal difficulties. Problems.```",
    ":small_red_triangle_down: » Downright card meaning\n**Ten of Swords:** ```bf\nTroubles passing. Relief. Need to rest.```",
    ":small_red_triangle: » Upright card meaning\n**Mother of Swords in the South (Nut):** ```bf\nA mysterious person. Devotion. Autonomy.```",
    ":small_red_triangle_down: » Downright card meaning\n**Mother of Swords in the South (Nut):** ```bf\nNeed for privacy exaggerated. Conflict between love of solitude and love for others.```",
    ":small_red_triangle: » Upright card meaning\n**Father of Swords in the South (Ra):** ```bf\nDominant, autocratic person. Delegating authority to others. Strong, creative intellect. Fairness.```",
    ":small_red_triangle_down: » Downright card meaning\n**Father of Swords in the South (Ra):** ```bf\nTyrant. A person jealous of personal powerful.```",
    ":small_red_triangle: » Upright card meaning\n**Daughter of Swords in the South (Isis):** ```bf\nA powerful figure, confident and dynamic.```",
    ":small_red_triangle_down: » Downright card meaning\n**Daughter of Swords in the South (Isis):** ```bf\nLoss of confidence. Depression.```",
    ":small_red_triangle: » Upright card meaning\n**Son of Swords in the South (Osiris):** ```bf\nSomeone gentle yet persuasive. An initiate into esoteric mysteries. Kindness.```",
    ":small_red_triangle_down: » Downright card meaning\n**Son of Swords in the South (Osiris):** ```bf\nWeakness, possibly corruption.```",
    ":small_red_triangle: » Upright card meaning\n**Ace of Stones:** ```bf\nHealth. Prosperity. Beauty. Good weather.```",
    ":small_red_triangle_down: » Downright card meaning\n**Ace of Stones:** ```bf\nUnappreciated gifts. Materialism. Conflicts over money or property.```",
    ":small_red_triangle: » Upright card meaning\n**Two of Stones:** ```bf\nHarmonic situations.```",
    ":small_red_triangle_down: » Downright card meaning\n**Two of Stones:** ```bf\nDisharmony. A time for solitude.```",
    ":small_red_triangle: » Upright card meaning\n**Three of Stones:** ```bf\nWork. Satisfaction.```",
    ":small_red_triangle_down: » Downright card meaning\n**Three of Stones:** ```bf\nWork not going well. Unemployment. Laziness.```",
    ":small_red_triangle: » Upright card meaning\n**Four of Stones:** ```bf\nCreativity and new ideas. Overwhelming energy.```",
    ":small_red_triangle_down: » Downright card meaning\n**Four of Stones:** ```bf\nLosing a sense of place. Fear.```",
    ":small_red_triangle: » Upright card meaning\n**Five of Stones:** ```bf\nWintry time. Money troubles. Illness. Isolation.```",
    ":small_red_triangle_down: » Downright card meaning\n**Five of Stones:** ```bf\nMovement for the better. Wait, act cautiously.```",
    ":small_red_triangle: » Upright card meaning\n**Six of Stones:** ```bf\nGreat success and joy, possibly short-lived. Find inner truth and happiness.```",
    ":small_red_triangle_down: » Downright card meaning\n**Six of Stones:** ```bf\nMoment beginning to end. Save or invest money carefully during prosperity.```",
    ":small_red_triangle: » Upright card meaning\n**Seven of Stones:** ```bf\nDisharmony. Without careful redirection, failure is possible.```",
    ":small_red_triangle_down: » Downright card meaning\n**Seven of Stones:** ```bf\nRecovery. Fresh Start.```",
    ":small_red_triangle: » Upright card meaning\n**Eight of Stones:** ```bf\nBe careful and moderate. Avoid excessive action.```",
    ":small_red_triangle_down: » Downright card meaning\n**Eight of Stones:** ```bf\nLack of moderation. Impatience. Ignorance.```",
    ":small_red_triangle: » Upright card meaning\n**Nine of Stones:** ```bf\nFortune. Money, security, health, comfort. Avoid complacency, greed or conceit.```",
    ":small_red_triangle_down: » Downright card meaning\n**Nine of Stones:** ```bf\nMisusing material gain. Greed.```",
    ":small_red_triangle: » Upright card meaning\n**Ten of Stones:** ```bf\nGood life. Health. A sense of solid reality.```",
    ":small_red_triangle_down: » Downright card meaning\n**Ten of Stones:** ```bf\nDelay. Not appreciating material wealth and security.```",
    ":small_red_triangle: » Upright card meaning\n**Mother of Stones in the West (Spider Woman):** ```bf\nSerene, probably older woman. Self-confidence.```",
    ":small_red_triangle_down: » Downright card meaning\n**Mother of Stones in the West (Spider Woman):** ```bf\nDifficulty in staying still and appreciating life. Loss of personal center.```",
    ":small_red_triangle: » Upright card meaning\n**Father of Stones in the West (Old Man):** ```bf\nFundamental male principle. Someone who cares deeply for family and for nature. Hard Worker.```",
    ":small_red_triangle_down: » Downright card meaning\n**Father of Stones in the West (Old Man):** ```bf\nCold and uncaring. Lack of success. Pain at the suffering of the world.```",
    ":small_red_triangle: » Upright card meaning\n**Daughter of Stones in the West (White Buffalo Woman):** ```bf\nWillingness to take responsibility for something greater than oneself. Love, courage, and dedication. Inner beauty.```",
    ":small_red_triangle_down: » Downright card meaning\n**Daughter of Stones in the West (White Buffalo Woman):** ```bf\nDifficulty getting across ideas or emotions. Feeling out of place.```",
    ":small_red_triangle: » Upright card meaning\n**Son of Stones in the West (Chief Seattle):** ```bf\nTaking action to make positive change - with the benefit of the next seven generations in mind.```",
    ":small_red_triangle_down: » Downright card meaning\n**Son of Stones in the West (Chief Seattle):** ```bf\nDespair. Selfishness leads to feeling lost.```"
]
